[package]
name = "risc-emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
elf = "0.8.0"
env_logger = "0.11.8"
log = "0.4.27"
raki = { path = "raki" }
